---
- name: Install nvm
  ansible.builtin.include_tasks: nvm.yml

- name: Install node
  ansible.builtin.include_tasks: node.yml

- name: Install npm packages
  ansible.builtin.include_tasks: pkgs.yml
  when: nvm_npm_pkgs | length > 0

# needed in order to preserve idempotency due to globally installed packages
- name: Fix nvm permissions
  ansible.builtin.include_tasks: permission.yml
