---
- name: Update .nvm dir ownership
  ansible.builtin.file:
    path: "{{ nvm_dest }}"
    group: "{{ nvm_group }}"
    owner: "{{ nvm_user }}"
    recurse: true
    state: directory
  become: true
  become_method: ansible.builtin.sudo

- name: Update .nvm dir mode
  ansible.builtin.file:
    path: "{{ nvm_dest }}"
    mode: "0755"
    state: directory
  become: true
  become_method: ansible.builtin.sudo

- name: Copy .npmrc
  ansible.builtin.template:
    src: ".npmrc.j2"
    dest: "{{ nvm_dest }}/.npmrc"
    owner: "{{ nvm_user }}"
    group: "{{ nvm_group }}"
    mode: "0600"
  when: npm_auth_token is defined and npm_auth_token != ''
