---

- name: update .nvm dir permission
  file:
    path: "{{ nvm_dest }}"
    group: "{{ nvm_group }}"
    owner: "{{ nvm_user }}"
    mode: 0755
    recurse: yes
    state: directory
  become: true
  become_method: sudo

- name: Copy .npmrc
  copy: src=".npmrc" dest="{{ nvm_dest }}" owner="{{ nvm_user }}" group="{{ nvm_group }}"
