---
- name: Update .nvm dir ownership
  ansible.builtin.file:
    path: "{{ nvm_dest }}"
    group: "{{ nvm_group }}"
    owner: "{{ nvm_user }}"
    recurse: true
    state: directory
  become: true
  become_method: sudo

- name: Update .nvm dir mode
  ansible.builtin.file:
    path: "{{ nvm_dest }}"
    mode: "0755"
    state: directory
  become: true
  become_method: sudo

- name: Copy .npmrc
  ansible.builtin.copy:
    src: ".npmrc"
    dest: "{{ nvm_dest }}"
    owner: "{{ nvm_user }}"
    group: "{{ nvm_group }}"
    mode: "0600"
