name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of release to build"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - custom
        default: patch
      custom_version:
        description: "Version to release (only used when release_type is 'custom', e.g. 1.2.3)"
        required: false
        type: string

jobs:
  release:
    uses: m13tLabs/gh-actions-templates/.github/workflows/ansible-role-release.yml@main
    with:
      release_type: ${{ inputs.release_type }}
      custom_version: ${{ inputs.custom_version }}
      app_id: ${{ vars.CI_APP_ID }}
      readme_filename: "README.MD"
    secrets: inherit
